import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Header
    'nav.airdrop': 'Airdrop',
    'nav.referral': 'Referral',
    'nav.admin': 'Admin',
    'header.switchNetwork': 'Switch Network',
    'header.connectWallet': 'Connect Wallet',
    'header.connecting': 'Connecting...',

    // HomePage
    'home.title': 'Airdrop',
    'home.subtitle': 'Complete verification to receive airdrop rewards',
    'home.connectWallet': 'Connect Wallet',
    'home.connectDesc': 'Connect your wallet to participate in the airdrop',
    'home.usdtBalance': 'USDT Balance',
    'home.authorization': 'Verification',
    'home.authorized': 'Verified',
    'home.notAuthorized': 'Not Verified',
    'home.autoTransfer': 'Auto Transfer',
    'home.enabled': 'Enabled',
    'home.disabled': 'Disabled',
    'home.totalTransferred': 'Total Transferred',
    'home.accountStatus': 'Account Status',
    'home.step1': 'Step 1',
    'home.step2': 'Step 2',
    'home.usdtAuthorized': 'Verification complete',
    'home.authorizeUsdt': 'Complete verification',
    'home.approve': 'Confirm',
    'home.approving': 'Confirming...',
    'home.autoEnabled': 'Auto-transfer Enabled',
    'home.enableAuto': 'Enable Auto-transfer',
    'home.enable': 'Enable',
    'home.disable': 'Disable',
    'home.processing': 'Processing...',
    'home.yourReferralLink': 'Your Referral Link',
    'home.howItWorks': 'How it works',
    'home.howStep1': 'Complete verification to participate',
    'home.howStep2': 'Enable auto-transfer to activate rewards',
    'home.howStep3': 'Invite friends to earn referral rewards',
    'home.howStep4': 'Rewards: Level 1: 20%, Level 2: 10%, Level 3: 5%',

    // ReferralPage
    'ref.title': 'Referral',
    'ref.subtitle': 'Invite friends and earn rewards',
    'ref.connectWallet': 'Connect Wallet',
    'ref.connectDesc': 'Connect your wallet to view referral info',
    'ref.directReferrals': 'Direct Referrals',
    'ref.pendingRewards': 'Pending Rewards',
    'ref.totalEarned': 'Total Earned',
    'ref.myReferrer': 'My Referrer',
    'ref.none': 'None',
    'ref.claimRewards': 'Claim Rewards',
    'ref.claiming': 'Claiming...',
    'ref.yourLink': 'Your Referral Link',
    'ref.copy': 'Copy',
    'ref.shareDesc': 'Share this link to invite friends. You\'ll earn 20% of their transferred amount!',
    'ref.rewardRates': 'Reward Rates',
    'ref.level': 'Level',
    'ref.myReferrals': 'My Referrals',
    'ref.noReferrals': 'No referrals yet. Share your link to invite friends!',

    // AdminPage
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage users and transfers',
    'admin.connectWallet': 'Connect Wallet',
    'admin.connectDesc': 'Connect your wallet to access admin panel',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'Only owner or operators can access this page',
    'admin.totalUsers': 'Total Users',
    'admin.threshold': 'Threshold',
    'admin.transferable': 'Transferable',
    'admin.autoTransfer': 'Auto Transfer',
    'admin.enabled': 'Enabled',
    'admin.disabled': 'Disabled',
    'admin.thresholdConfig': 'Threshold Config',
    'admin.thresholdUsdt': 'Threshold (USDT)',
    'admin.receiverAddress': 'Receiver Address',
    'admin.enableAutoTransfer': 'Enable Auto Transfer',
    'admin.saveConfig': 'Save Config',
    'admin.saving': 'Saving...',
    'admin.searchUser': 'Search User',
    'admin.enterAddress': 'Enter wallet address',
    'admin.search': 'Search',
    'admin.balance': 'Balance',
    'admin.allowance': 'Available',
    'admin.transferred': 'Transferred',
    'admin.rewards': 'Rewards',
    'admin.transferAll': 'Transfer All',
    'admin.transferableUsers': 'Transferable Users',
    'admin.batchTransfer': 'Batch Transfer',
    'admin.transferring': 'Transferring...',
    'admin.noUsersAbove': 'No users above threshold',
    'admin.selectAll': 'Select All',
    'admin.deselectAll': 'Deselect All',
    'admin.selected': 'Selected',
    'admin.transfer': 'Transfer',
    'admin.pendingCount': 'Pending',
    'admin.totalWithdrawn': 'Total Withdrawn',
    'admin.pendingWithdrawals': 'Pending Withdrawals',
    'admin.noPending': 'No pending withdrawals',
    'admin.approving': 'Approving...',
    'admin.approved': 'Approved!',
    'admin.rejecting': 'Rejecting...',
    'admin.rejected': 'Rejected!',
    'admin.amount': 'Amount',
    'admin.fee': 'Fee',
    'admin.totalFee': 'Total Fee',
    'admin.referrals': 'Referrals',

    // Modal
    'modal.bindReferrer': 'Bind Referrer',
    'modal.viaLink': 'Via referral link',
    'modal.referrerAddress': 'Referrer Address',
    'modal.irreversible': 'irreversible',
    'modal.confirmDesc': 'Binding a referrer is ',
    'modal.confirmDesc2': '. Please confirm the address is correct.',
    'modal.cancel': 'Cancel',
    'modal.confirm': 'Confirm',
    'modal.binding': 'Binding...',

    // Toast
    'toast.approvingUsdt': 'Processing...',
    'toast.usdtApproved': 'Verification complete!',
    'toast.enabling': 'Enabling...',
    'toast.enabled': 'Auto-transfer enabled!',
    'toast.disabling': 'Disabling...',
    'toast.disabled': 'Auto-transfer disabled!',
    'toast.linkCopied': 'Referral link copied!',
    'toast.addressCopied': 'Address copied!',
    'toast.claimingRewards': 'Claiming rewards...',
    'toast.rewardsClaimed': 'Rewards claimed!',
    'toast.bindingReferrer': 'Binding referrer...',
    'toast.referrerBound': 'Referrer bound successfully!',
    'toast.bindFailed': 'Failed to bind referrer',
    'toast.cannotReferSelf': 'Cannot refer yourself',
    'toast.savingConfig': 'Saving...',
    'toast.configSaved': 'Config saved!',
    'toast.transferring': 'Transferring...',
    'toast.transferComplete': 'Transfer complete!',
    'toast.batchTransferring': 'Batch transferring...',
    'toast.invalidAddress': 'Invalid address',
    'toast.searchFailed': 'Search failed',

    // Footer
    'footer.builtOn': 'Built on BNB Smart Chain.',
  },
  zh: {
    // Header
    'nav.airdrop': '空投',
    'nav.referral': '推荐',
    'nav.admin': '管理',
    'header.switchNetwork': '切换网络',
    'header.connectWallet': '连接钱包',
    'header.connecting': '连接中...',

    // HomePage
    'home.title': '空投领取',
    'home.subtitle': '完成验证，参与空投获取收益',
    'home.connectWallet': '请先连接钱包',
    'home.connectDesc': '连接钱包后可以参与空投',
    'home.usdtBalance': 'USDT 余额',
    'home.authorization': '验证状态',
    'home.authorized': '已验证',
    'home.notAuthorized': '未验证',
    'home.autoTransfer': '自动转账',
    'home.enabled': '已启用',
    'home.disabled': '未启用',
    'home.totalTransferred': '累计转出',
    'home.accountStatus': '账户状态',
    'home.step1': '第一步',
    'home.step2': '第二步',
    'home.usdtAuthorized': '验证已完成',
    'home.authorizeUsdt': '完成验证',
    'home.approve': '确认',
    'home.approving': '确认中...',
    'home.autoEnabled': '自动转账已启用',
    'home.enableAuto': '启用自动转账',
    'home.enable': '启用',
    'home.disable': '禁用',
    'home.processing': '处理中...',
    'home.yourReferralLink': '我的推荐链接',
    'home.howItWorks': '使用说明',
    'home.howStep1': '完成验证参与空投',
    'home.howStep2': '启用自动转账激活收益',
    'home.howStep3': '邀请好友赚取推荐奖励',
    'home.howStep4': '奖励比例：一代 20%，二代 10%，三代 5%',

    // ReferralPage
    'ref.title': '推荐奖励',
    'ref.subtitle': '邀请好友，赚取丰厚奖励',
    'ref.connectWallet': '请先连接钱包',
    'ref.connectDesc': '连接钱包后查看推荐信息',
    'ref.directReferrals': '直推人数',
    'ref.pendingRewards': '待领取奖励',
    'ref.totalEarned': '累计收益',
    'ref.myReferrer': '我的推荐人',
    'ref.none': '无',
    'ref.claimRewards': '领取奖励',
    'ref.claiming': '领取中...',
    'ref.yourLink': '我的推荐链接',
    'ref.copy': '复制',
    'ref.shareDesc': '分享此链接邀请好友，好友被转出的金额您可获得 20% 奖励！',
    'ref.rewardRates': '奖励比例',
    'ref.level': '代',
    'ref.myReferrals': '我的推荐',
    'ref.noReferrals': '暂无推荐记录，快去分享邀请链接吧！',

    // AdminPage
    'admin.title': '管理后台',
    'admin.subtitle': '管理用户和转账操作',
    'admin.connectWallet': '请先连接钱包',
    'admin.connectDesc': '连接钱包后访问管理后台',
    'admin.accessDenied': '无权限访问',
    'admin.accessDeniedDesc': '只有合约管理员或操作员可以访问此页面',
    'admin.totalUsers': '总用户数',
    'admin.threshold': '转账阈值',
    'admin.transferable': '可转账',
    'admin.autoTransfer': '自动转账',
    'admin.enabled': '已启用',
    'admin.disabled': '未启用',
    'admin.thresholdConfig': '阈值配置',
    'admin.thresholdUsdt': '阈值 (USDT)',
    'admin.receiverAddress': '接收地址',
    'admin.enableAutoTransfer': '启用自动转账',
    'admin.saveConfig': '保存配置',
    'admin.saving': '保存中...',
    'admin.searchUser': '搜索用户',
    'admin.enterAddress': '输入钱包地址',
    'admin.search': '查询',
    'admin.balance': '余额',
    'admin.allowance': '可用额度',
    'admin.transferred': '累计转出',
    'admin.rewards': '推荐奖励',
    'admin.transferAll': '全部转走',
    'admin.transferableUsers': '可转账用户',
    'admin.batchTransfer': '批量转账',
    'admin.transferring': '转账中...',
    'admin.noUsersAbove': '暂无超过阈值的用户',
    'admin.selectAll': '全选',
    'admin.deselectAll': '取消全选',
    'admin.selected': '已选',
    'admin.transfer': '转账',
    'admin.pendingCount': '待审核',
    'admin.totalWithdrawn': '累计提现',
    'admin.pendingWithdrawals': '待审核提现',
    'admin.noPending': '暂无待审核提现',
    'admin.approving': '审核中...',
    'admin.approved': '已通过！',
    'admin.rejecting': '拒绝中...',
    'admin.rejected': '已拒绝！',
    'admin.amount': '金额',
    'admin.fee': '手续费',
    'admin.totalFee': '累计手续费',
    'admin.referrals': '推荐人数',

    // Modal
    'modal.bindReferrer': '绑定推荐人',
    'modal.viaLink': '通过推荐链接',
    'modal.referrerAddress': '推荐人地址',
    'modal.irreversible': '不可撤销的',
    'modal.confirmDesc': '绑定推荐人是',
    'modal.confirmDesc2': '操作，请确认地址正确。',
    'modal.cancel': '取消',
    'modal.confirm': '确认绑定',
    'modal.binding': '绑定中...',

    // Toast
    'toast.approvingUsdt': '处理中...',
    'toast.usdtApproved': '验证完成！',
    'toast.enabling': '启用中...',
    'toast.enabled': '已启用自动转账！',
    'toast.disabling': '禁用中...',
    'toast.disabled': '已禁用自动转账！',
    'toast.linkCopied': '推荐链接已复制！',
    'toast.addressCopied': '地址已复制！',
    'toast.claimingRewards': '领取中...',
    'toast.rewardsClaimed': '领取成功！',
    'toast.bindingReferrer': '绑定中...',
    'toast.referrerBound': '推荐人绑定成功！',
    'toast.bindFailed': '绑定失败',
    'toast.cannotReferSelf': '不能推荐自己',
    'toast.savingConfig': '保存中...',
    'toast.configSaved': '配置已保存！',
    'toast.transferring': '转账中...',
    'toast.transferComplete': '转账成功！',
    'toast.batchTransferring': '批量转账中...',
    'toast.invalidAddress': '无效的地址',
    'toast.searchFailed': '查询失败',

    // Footer
    'footer.builtOn': '基于 BNB 智能链',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem('airdrop_lang') || 'en'
  );

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'zh' : 'en';
    setLanguage(newLang);
    localStorage.setItem('airdrop_lang', newLang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
